on:
  pull_request:
    types:
      - closed

jobs:
   dev:
      name: Deploy to AWS Dev
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install Python dependencies
          uses: py-actions/py-dependency-install@v4
          with:
            path: "files/lambda/requirements.txt"

        - name: terraform version
          run: terraform --version

        - name: terraform init
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform init -backend-config="backend_s3_dev.tfbackend" -input=false -reconfigure

        - name: terraform validation
          run: terraform validate

        - name: terraform apply
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #run: terraform apply -var-file=dev.tfvars -auto-approve -input=false
          run: terraform plan -var-file=dev.tfvars -input=false

        - run: |
            echo The PR was merged
          
   preprod:
      name: Deploy to AWS -Preprod environments
      needs: dev
      runs-on: ubuntu-latest
      environment: pre-prod
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install Python dependencies
          uses: py-actions/py-dependency-install@v4
          with:
            path: "files/lambda/requirements.txt"

        - name: terraform version
          run: terraform --version

        - name: terraform init
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PREPROD }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PREPROD }}
          run: terraform init -backend-config="backend_s3_preprod.tfbackend" -input=false -reconfigure

        - name: terraform validation
          run: terraform validate

        - name: terraform apply 
          #env:
            #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PREPROD }}
            #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PREPROD }}
	  #run: terraform apply -var-file=preprod.tfvars -auto-approve -input=false
          run: terraform plan -var-file=preprod.tfvars -input=false

        - run: |
            echo The PR was merged      
